name: discount_calculator
description: "A Discount Calculator with History"
publish_to: 'none'

version: 1.1.1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0 # state management
  flutter_slidable: ^3.1.2 # for sliding widgets
  gap: ^3.0.1 # for responsive design
  intl: ^0.20.1 # for date formatting
  sqflite: ^2.4.1 # for local storage
  uuid: ^4.5.1 # for unique id generation

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  lint_hard: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/discount.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/discount.png"
  web:
    generate: true
    image_path: "assets/discount.png"

