// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQEBY9x8Ukt_uy3ytOqFZ2avtEwpUSCNU',
    appId: '1:160564439486:web:f18f1caea63f9a13d4f1ef',
    messagingSenderId: '160564439486',
    projectId: 'discount-calculator-7a452',
    authDomain: 'discount-calculator-7a452.firebaseapp.com',
    storageBucket: 'discount-calculator-7a452.firebasestorage.app',
    measurementId: 'G-EMM75SH17J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVSRezGeoy9QcTfAUNZkjspDbxuFs6OUc',
    appId: '1:160564439486:android:000318d329585466d4f1ef',
    messagingSenderId: '160564439486',
    projectId: 'discount-calculator-7a452',
    storageBucket: 'discount-calculator-7a452.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2bli9gUwcEjQs2GHFGjMlC5B0A0SnLhc',
    appId: '1:160564439486:ios:20d231f6616f6239d4f1ef',
    messagingSenderId: '160564439486',
    projectId: 'discount-calculator-7a452',
    storageBucket: 'discount-calculator-7a452.firebasestorage.app',
    iosBundleId: 'com.josephvalle.discount.discountCalculator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2bli9gUwcEjQs2GHFGjMlC5B0A0SnLhc',
    appId: '1:160564439486:ios:20d231f6616f6239d4f1ef',
    messagingSenderId: '160564439486',
    projectId: 'discount-calculator-7a452',
    storageBucket: 'discount-calculator-7a452.firebasestorage.app',
    iosBundleId: 'com.josephvalle.discount.discountCalculator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQEBY9x8Ukt_uy3ytOqFZ2avtEwpUSCNU',
    appId: '1:160564439486:web:aa8afd738c7c78b9d4f1ef',
    messagingSenderId: '160564439486',
    projectId: 'discount-calculator-7a452',
    authDomain: 'discount-calculator-7a452.firebaseapp.com',
    storageBucket: 'discount-calculator-7a452.firebasestorage.app',
    measurementId: 'G-LMHERBH1LD',
  );
}
